spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/blahajbot
        username: 
        password: 
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format-sql: true
    quartz:
        job-store-type: jdbc
        properties:
            org:
                quartz:
                    jobStore:
                        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
    security:
        oauth2:
            client:
                registration:
                    discord:
                        client-id:
                        client-secret:
                        authorization-grant-type: authorization_code
                        scope: identify, guilds
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        clientName: Blahajbot
                provider:
                    discord:
                        authorization-uri: 
                        token-uri: https://discordapp.com/api/oauth2/token
                        user-info-uri: https://discordapp.com/api/users/@me
                        user-name-attribute: username
server:
    port: 8056
logging:
    level:
        org:
            springframework:
                security: DEBUG
token:
frontend-url: http://localhost:5173